### ISSUE TITLE
Where these files located AnWeMoSc1S001R01_ds10_1-12.BBCI.mat

### ISSUE THREAD

**Issue by dhananjaisrmgpc** [robintibor/braindevel#1]
Completed all installations successfully, though in last step it says "Work with real data"Create folder <repositoryfolder>/data/BBCI-without-last-runs/ and put the file called AnWeMoSc1S001R01_ds10_1-12.BBCI.mat
Where exactly are those files located ?

**Comment by robintibor** [comment]
Please don't try to use this code haha
Use code here: https://github.com/TNTLFreiburg/braindecode and here https://gin.g-node.org/robintibor/high-gamma-dataset
